services:
    _defaults:
        autowire: true
        autoconfigure: true

    Rallo\ContaoPdfImport\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Resources/'
            - '../src/ContaoPdfImportBundle.php'
